### ISSUE TITLE
'Hide Tokens and URLs on Other Lines' tip hides everything on current line as well

### ISSUE THREAD

**Issue by korg91** [CalebJohn/joplin-rich-markdown#27]
I've been using Rich Markdown for some time and I absolutely love that it can [hide tokens and URLs on other lines](https://github.com/CalebJohn/joplin-rich-markdown/blob/main/TIPS.md#hide-tokens-and-urls-on-other-lines). Now the CSS tip does not work as intended anymore (probably because of a Joplin and/or RM update).  The tokens and the URLs are now hidden on the current line as well, making it impossible to edit the text. I can replicate the issue even on a clean installation.

However, it looks like the CSS tip works as intended if I activate _Highlight the background of the current line_ in setting. Is there any way to hide tokens and URLs without enabling the background?

Thanks!

![image](https://user-images.githubusercontent.com/3729408/139539896-8ec3e08a-3072-4e1c-93bb-54da37207cd8.png)

![image](https://user-images.githubusercontent.com/3729408/139539928-37e1afb4-179a-4ff9-b01c-af3c60906256.png)

**Comment by CalebJohn** [comment]
Hi @korg91 

Thanks for pointing this out! There is no way to hide the tokens without enabling the background, but it is easy to hide the background with CSS. I'll update the TIPS section to reflect that this needs to be done.
This is the new CSS that you need to add in order to hide the background colour on active lines.

```css
/* Optional: You might also want to disable the highlight background */
.CodeMirror .CodeMirror-activeline
.CodeMirror-activeline-background:not(.cm-jn-code-block):not(.cm-jn-code-block-background),
.cm-s-solarized.cm-s-light div.CodeMirror-activeline-background,
.cm-s-solarized.cm-s-dark div.CodeMirror-activeline-background {
  background: inherit;
}
```
