### ISSUE TITLE
Feature Request: Monspace font for code and code blocks

### ISSUE THREAD

**Issue by andi0b** [CalebJohn/joplin-rich-markdown#3]
Thanks for this awesome plugin!

I use now Arial for the Markdown, but I would like to use a monospace font for code, like here on Github:

---
Arial Arial Arial `monospace monospace`

```
monospace monospace monospace
```
---

Sadly there is no css class for code blocks, the best i could do was this, but it doesn't select spaces and brackets in between the elements.

```css
/* code */
 span.cm-comment
,span.cm-keyword
,span.cm-def
,span.cm-type
,span.cm-operator
,span.cm-string
,span.cm-variable
,span.cm-property
,span.cm-builtin {
  font-family: "Jetbrains Mono" !important;
}
```

Like you can see the `[]` is still Arial, also the `..`
![grafik](https://user-images.githubusercontent.com/2432095/112819529-fa0a6480-9084-11eb-8930-39f6bd5b2173.png)
